Milestone 3 completion
Guy-Gustave/Bookstore pull request #4
Opened 2021-04-16 11:40 UTC by RNtaate

## What does this PR do?
- [X] Connects the `CREATE_BOOK` and `REMOVE_BOOK` actions to the component.
- [X] Makes the `BooksForm ` component stateful.

2021-04-16 14:19 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @RNtaate and @Guy-Gustave, congratulations on  this milestone :fireworks: The BookForm, BookList, and the Book component neatly design :slightly_smiling_face: However, we got a few comments to address before approving this milestone: Kindly check the comments below:
- Kindly add a title and a description of the Project in the README file so anybody can actually know what is going on there
- Also, one thing to fix in the BookForm component is to change the `onClick` event to `onSubmit` which is what we intend to do

Once these are resolved, kindly submit another code review request :slightly_smiling_face: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-04-16 14:19 UTC, addod19 commented on src/containers/BooksForm.js
> +      <button type="button" onClick={handleSubmit}>Submit</button>
Kindly change the `onClick` event handler to `onSubmit` which is more descriptive

2021-04-16 15:16 UTC, RNtaate commented
## Changes made
 - [X] Changed `onClick` event handler to `onSubmit` event handler in BooksForm component.
 - [X] Updated readme file with a  project title and description.

2021-04-17 00:17 UTC, uryelah approved these changes
Hi **Roy Ntaate & Guy Nigaba** , I'm Sarah your reviewer for this PR 👩‍🚀 

Great job implementing the requests from the last reviewer!
I specially like your creativity in handling the change events for the inputs.

Your project is approved but I mention some optional changes that can improve your project a little so consider checking them out before merging 😉 

Keep on coding and Rock on! 🎸 👨‍🎤 

# Approved 🚀 🎉 

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2021-04-17 00:17 UTC, uryelah commented on src/components/Book.js
>  const Book = (props) => {
- [ ] [OPTIONAL] You can destruct the props in the declaration line of the component in order to save lines of code:
```javaScript
const Book = ({book, remove}) => {
```

2021-04-17 00:17 UTC, uryelah commented on src/components/Book.js
>  };
- [ ] [OPTIONAL] The remove function not being passed as a prop would basically break one of the functionalities of the app, right?
That means it should be a required prop, with no need of a default prop value.

2021-04-17 00:17 UTC, uryelah commented on src/containers/BooksForm.js
> +  };
Interesting implementation you did her with the switch case logic.
Can you think of a why to avoid repeating the setLocalBook call?

2021-04-17 11:13 UTC, merged